# .github/workflows/workflow.yml
name: CI/CD WORKFLOW
on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn --batch-mode -DskipTests clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Build & push API image ---
      - name: Build & push API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webscraper_api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/webscraper_api
      # --- Build & push CRAWLER image ---
      - name: Build & push Crawler image
        uses: docker/build-push-action@v6
        with:
          context: ./crawler
          file: ./crawler/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webscraper-crawler:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/webscraper-crawler
